# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: The Tengine Web Server
subtitle:
description:
author: soulteary{at}Aliyun/UED Team
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://tengine.taobao.org/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true

highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# RSS
feed:
  type:   atom
  path:   atom.xml
  limit:  20
  hub:
# - **type** - Feed type. (atom/rss2)
# - **path** - Feed path. (Default: atom.xml/rss2.xml)
# - **limit** - Maximum number of posts in the feed (Use `0` or `false` to show all posts)
# - **hub** - URL of the PubSubHubbub hubs (Leave it empty if you don't use it)

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: owl

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:


#deploy:
#  type: git ##部署類型 其他類型自行google之
#  repo: <repository url> ##git倉庫地址
#  branch: [branch] ##git 頁面分支
#  message: [message] ##git message建議默認字段update 可以自定義


sitemap:
  path:     sitemap.xml

## Excluding pages or posts
# You can exclude pages or posts from the sitemap by adding `sitemap: false` to the relevant front-matter.

auto_spacing:
  enable:   false
  title:    true
  content:  false



nofollow:
  enable:   true
  exclude:
            - exclude1.com
            - exclude2.com

html_minifier:
  enable:             true
  collapseWhitespace: true
  exclude:



marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: false
  smartypants: false

